# Generated by Django 6.0.3 on 2026-03-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_tag_product_sku_product_stock_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="img_link",
            field=models.URLField(
                blank=True,
                help_text="External image URL (alternative to uploading)",
                null=True,
            ),
        ),
    ]
