# Generated by Django 6.0.3 on 2026-03-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_category_products_ca_slug_da4386_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_pr_brand_i_dc6890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock"], name="products_pr_stock_4d23d5_idx"),
        ),
    ]
