# Generated by Django 6.0.3 on 2026-03-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_products_pr_brand_i_dc6890_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Arabic)"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Arabic)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True, verbose_name="Description (Arabic)"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Name (Arabic)"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ar",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Name (Arabic)"
            ),
        ),
    ]
