# Generated by Django 6.0.3 on 2026-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_cartitem_cartitem_cart_idx"),
        ("products", "0006_product_products_pr_brand_i_dc6890_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="cartitem_product_idx"),
        ),
    ]
