# Generated by Django 6.0.3 on 2026-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                (
                    "image_mobile",
                    models.ImageField(
                        blank=True,
                        help_text="Optional mobile-specific image",
                        upload_to="banners/mobile/",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.TextField(blank=True)),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Arabic)"
                    ),
                ),
                (
                    "subtitle_ar",
                    models.TextField(blank=True, verbose_name="Subtitle (Arabic)"),
                ),
                ("link", models.URLField(blank=True)),
                ("link_text", models.CharField(blank=True, max_length=50)),
                (
                    "link_text_ar",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Link Text (Arabic)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["order"],
            },
        ),
    ]
